### PR TITLE
Add lockfile json schema, validation, unit tests, and an incomplete integration test

### PR DESCRIPTION
**Pull request by willhansen**
Some initial steps for lockfile validation.  

Remaining to do after this:
- More validation checks
- Get the integration test passing, and add more of them

### CODE REVIEW

**Comment by rndhouse** [comment]
Thank you, that's great! I like the direction.

Would you mind giving me access as a maintainer to add commits to your branch? See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on how to do that. I would like to add a few commits (whilst allowing you to add more also if you wish).

I think there's an important bit missing. The tests added in this PR examine the JSON scheme. But `openfare` could still generate lock files which don't follow the JSON scheme.

The `Lock` structure `openfare` uses to generate lock files is defined [here](https://github.com/openfare/openfare/blob/ed2faa72fa049d0c45d5cd97a244c9a66ddb71ec/openfare-lib/src/lock/mod.rs#L10). I think that the tests should use `struct Lock` to generate lock JSON strings as opposed to using static `.lock` files. That way we can be sure that the lock files generated by the openfare tool follow the scheme.

**Comment by willhansen** [comment]
No prob.

Also, I definitely agree on generating and then modifying lock files for tests.  Any schema change mandates that all the static test files be updated by hand, which is _already_ a headache.  That's just for testing validation though.  I think the correct place for making sure generation and validation are consistent is the higher-level integration tests.

**Comment by willhansen** [comment]
It's now generating lockfiles instead of using static ones, and the integration test is now passing a basic check for consistency.

**Comment by rndhouse** [comment]
Thanks @willhansen , great to get this going.

**Pull request merged**
